Modelo ParentGroup añadido
decide-part-chullo/decide pull request #15
Opened 2021-12-15 08:04 UTC by jesvarzam

Se ha creado el modelo ParentGroup y se ha añadido al template de admin

2021-12-16 16:07 UTC, jesvarzam commented
Por algún motivo que desconozco, el test delete_group no consigue funcionar como debería. En concreto, a la hora de hacer el assertEquals para comprobar que no existe ningún ParentGroup creado, se produce una excepción, ya que no se ha borrado el grupo creado.

2021-12-16 16:30 UTC, jesvarzam commented
Para probar la funcionalidad creada, basta con acceder a la vista de admin. En ella, debe aparecer un apartado en Census llamado ParentGroup. Accediendo a él, se puede crear un ParentGroup, cuyos datos necesarios son el nombre del grupo a crear, los permisos a otorgar y decidir si es un grupo público o privado. Se muestran imágenes de la interfaz. 

![Captura de pantalla de 2021-12-16 17-27-08](https://user-images.githubusercontent.com/72498906/146410556-c8da0e7c-1447-4e7f-b8d6-0fec62a1dfdf.png)

![Captura de pantalla de 2021-12-16 17-27-24](https://user-images.githubusercontent.com/72498906/146410620-3202794b-0a26-4a72-9335-c95730eea661.png)

![Captura de pantalla de 2021-12-16 17-27-30](https://user-images.githubusercontent.com/72498906/146410641-107e76a2-d93f-4186-8729-d0ac99c1a946.png)

2021-12-17 10:00 UTC, mangarmar requested changes
Cuando hago clic en ParentGroup me da error.
![Captura de pantalla de 2021-12-17 10-58-33](https://user-images.githubusercontent.com/72518616/146526586-c3e347af-c0f9-4599-b1ff-cbd05d432390.png)

2021-12-17 10:20 UTC, jesvarzam commented
El error debería ocurrir porque es necesario realizar tanto el makemigrations como el migrate una vez importada la rama, puesto que la funcionalidad se trata de un nuevo modelo creado.

2021-12-17 10:24 UTC, mangarmar approved these changes

2021-12-17 10:47 UTC, merged