Método inicial establecido y plantilla creada
decide-part-chullo/decide pull request #45
Opened 2021-12-21 19:42 UTC by JuanjoLv

2021-12-21 20:28 UTC, mangarmar requested changes
Cuando una votación esta creada pero no empezada, aparece dentro de las votaciones abiertas y al clicar al enlace da un 404 not found. Es por que el enlace redirige a booth y si la votación no ha comenzado la cabina no esta abierta.

2021-12-21 21:28 UTC, mangarmar approved these changes

2021-12-24 13:19 UTC, alvcorcas reviewed
@JuanjoLv 

La funcionalidad marcha como se espera, aunque se debería extraer del módulo auth puesto que no tiene que ver con la autenticación.
¿Hay algún motivo por el qué puedas ver la votaciones abiertas, pendientes y cerradas de un usuario que no es el que tiene la sesión iniciada?

2022-01-04 20:08 UTC, mangarmar requested changes
En votaciones cerradas solo deberían aparecer las votaciones que ya hayan pasado por el tally, ya que si no está hecho no se puede acceder a la página del enlace.

2022-01-07 10:40 UTC, mangarmar approved these changes

2022-01-07 10:41 UTC, merged